export const SzablonyActionTypes = {
  GET_ALL_SZABLONS_START: "GET_ALL_SZABLONS_START",
  GET_ALL_SZABLONS_SUCCESS: "GET_ALL_SZABLONS_SUCCESS",
  GET_ALL_SZABLONS_ERROR: "GET_ALL_SZABLONS_ERROR",

  SEARCH_SZABLON_START: "SEARCH_SZABLON_START",
  SEARCH_SZABLON_SUCCESS: "SEARCH_SZABLON_SUCCESS",
  SEARCH_SZABLON_ERROR: "SEARCH_SZABLON_ERROR",

  DELETE_SZABLON_START: "DELETE_SZABLON_START",
  DELETE_SZABLON_SUCCESS: "DELETE_SZABLON_SUCCESS",
  DELETE_SZABLON_ERROR: "DELETE_SZABLON_ERROR",

  GET_SZABLON: "GET_SZABLON",

  UPDATE_SZABLON_START: "UPDATE_SZABLON_START",
  UPDATE_SZABLON_SUCCESS: "UPDATE_SZABLON_SUCCESS",
  UPDATE_SZABLON_ERROR: "UPDATE_SZABLON_ERROR",

  ADD_SZABLON_START: "ADD_SZABLON_START",
  ADD_SZABLON_SUCCESS: "ADD_SZABLON_SUCCESS",
  ADD_SZABLON_ERROR: "ADD_SZABLON_ERROR",

  SEARCH_SZABLON_TABLE_START: "SEARCH_SZABLON_TABLE_START",
  SEARCH_SZABLON_TABLE_SUCCESS: "SEARCH_SZABLON_TABLE_SUCCESS",
  SEARCH_SZABLON_TABLE_ERROR: "SEARCH_SZABLON_TABLE_ERROR",

  STORE_SZABLON_START: "STORE_SZABLON_START",
  STORE_SZABLON_SUCCESS: "STORE_SZABLON_SUCCESS",
  STORE_SZABLON_ERROR: "STORE_SZABLON_ERROR",

  GET_SZABLON_FOR_PCB_START: "GET_SZABLON_FOR_PCB_START",
  GET_SZABLON_FOR_PCB_SUCCESS: "GET_SZABLON_FOR_PCB_SUCCESS",
  GET_SZABLON_FOR_PCB_ERROR: "GET_SZABLON_FOR_PCB_ERROR",

  GET_SZABLON_PAGE_START: "GET_SZABLON_PAGE_START",
  GET_SZABLON_PAGE_SUCCESS: "GET_SZABLON_PAGE_SUCCESS",
  GET_SZABLON_PAGE_ERROR: "GET_SZABLON_PAGE_SUCCESS",

  GET_SZABLON_COUNT_START: "GET_SZABLON_COUNT_START",
  GET_SZABLON_COUNT_SUCCESS: "GET_SZABLON_COUNT_SUCCESS",
  GET_SZABLON_COUNT_ERROR: "GET_SZABLON_COUNT_ERROR",

  GET_SZABLON_AFTER_UPDATE_START: "GET_SZABLON_AFTER_UPDATE_START",
  GET_SZABLON_AFTER_UPDATE_SUCCESS: "GET_SZABLON_AFTER_UPDATE_SUCCESS",
  GET_SZABLON_AFTER_UPDATE_ERROR: "GET_SZABLON_AFTER_UPDATE_ERROR"
};
