export const UserActionTypes = {
  GET_USER_FROM_ID_START: "GET_USER_FROM_ID_START",
  GET_USER_FROM_ID_SUCCESS: "GET_USER_FROM_ID_SUCCESS",
  GET_USER_FROM_ID_ERROR: "GET_USER_FROM_ID_ERROR",

  SIGNIN_START: "SIGNIN_START",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_ERROR: "SIGNIN_ERROR"
};
